### ISSUE TITLE
jump to character

### ISSUE THREAD

**Issue by kennethkoontz** [leny/atom-easy-motion-redux#1]
Thanks for rewriting this package due to the deprecation warnings in the original package.

It would be awesome if features in this package could reach parity with [vim's implementation](https://github.com/easymotion/vim-easymotion).

One feature that I like is jumping to a character instead of word.

**Comment by leny** [comment]
Hi, thanks for the report.

It was originally a fast clone/rewriting of the package due to the lack of response from the original creator, rushing a bit to have a functional plugin before `Atom 1.0`.

For now, I'm quite busy with pro work, so, if you want to submit a Pull Request, be my guest. :)

**Comment by liam-ngy** [comment]
Would be great if you can do it some day :)

**Comment by leny** [comment]
Don't have much time right now, too much pro work. Feel free to submit a Pull Request. :)

**Comment by leny** [comment]
Hi, sorry for the _very_ long time on this. Had a busy year.

I've just released the version `1.0.0` of the package, including three modes of jumping : **words** (the default behavior), **letter** (jumping to a character, as you asked), and **words_starting** (jumping to words starting with a character).

Hope you'll like it.

Sorry again for the long wait.
