### ISSUE TITLE
"Words starting with letter" doesn't recognise words at the start of a line

### ISSUE THREAD

**Issue by lijuenc** [leny/atom-easy-motion-redux#13]
![easymotion](https://cloud.githubusercontent.com/assets/4900094/15525018/b097775e-2269-11e6-8582-359664c290e0.png)

In the first paragraph the word "Lorem" is the first word of the line.
In the second paragraph there is a space before the word "Lorem".

When using Words starting with letter and typing "L", the first instance of "Lorem" isn't tagged but the second instance is.

Is this intended?

**Comment by leny** [comment]
Nope, it's not intended. Thanks for the report 👍 

I'm quite busy right now with pro work, will try to fix it as soon as I can. Feel free to dig into the code and submit a Pull Request if you want!

**Comment by leny** [comment]
Fixed & published as `1.1.1`.

Thanks again for the report.
