### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by RaNKaR** [leny/atom-easy-motion-redux#15]
## steps to reproduce
1. try to select any symbol by 'easy-motion-redux:letter'
2. realize that it's not that symbol that you want
3. press Backspace

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package, v1.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of null

**Comment by roman-yakobnyuk** [comment]
+1

**Comment by liam-ngy** [comment]
+1

**Comment by forsigner** [comment]
+1

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)

**Comment by wabilin** [comment]
Fixed in #16 ✌️
