### ISSUE TITLE
TextEditor.onDidChangeScrollTop is deprecated.

### ISSUE THREAD

**Issue by PhilShaughnes** [leny/atom-easy-motion-redux#17]
This is now a view method. Call TextEditorElement::onDidChangeScrollTop instead.
```
TextEditor.onDidChangeScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:697:12)
InputView.handleEvents (/Users/phil/.atom/packages/easy-motion-redux/lib/views/input.js:120:56)
InputView.initialize (/Users/phil/.atom/packages/easy-motion-redux/lib/views/input.js:77:18)
InputView.constructor (/Users/phil/.atom/packages/easy-motion-redux/node_modules/space-pen/lib/space-pen.js:184:25)
new InputView (/Users/phil/.atom/packages/easy-motion-redux/lib/views/input.js:56:79)
_fStart (/Users/phil/.atom/packages/easy-motion-redux/lib/main.js:29:18)
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)
