### ISSUE TITLE
TextEditor.getScrollLeft is deprecated.

### ISSUE THREAD

**Issue by samuelmburu** [leny/atom-easy-motion-redux#21]
This is now a view method. Call TextEditorElement::getScrollLeft instead.
```
TextEditor.getScrollLeft (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3538:12)
InputView.getColumnRangeForRow (/Users/samuelmburu/.atom/packages/easy-motion-redux/lib/views/input.js:391:49)
<unknown> (/Users/samuelmburu/.atom/packages/easy-motion-redux/lib/views/input.js:366:31)
Array.map (native)
InputView.getRowRanges (/Users/samuelmburu/.atom/packages/easy-motion-redux/lib/views/input.js:365:45)
InputView.loadPositions (/Users/samuelmburu/.atom/packages/easy-motion-redux/lib/views/input.js:343:40)
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)
