### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by ezhlobo** [leny/atom-easy-motion-redux#23]
@leny hey, thank you for your work on this package. It's pretty good!

But now I see that you are not able (have no time I guess) to support this package. I believe that you need to find a new contributor because it's published and useful package.

You can randomly ask your colleagues (or other contributors), there is a chance that someone can do it.

What do you think about?

**Comment by leny** [comment]
Hi, thanks for your message!

As you guessed, I'm not really active into maintaining this package (nor any of mine Atom packages), for two reasons : a critical lack of time, and mostly the fact that I'm not using Atom anymore (switched to vim a year ago).

I will be very glad to accept as collaborator any __githuber__ that will request it here. 

Maybe you?

**Comment by ezhlobo** [comment]
I would suggest myself as a collaborator but to be honest I can handle some issues and PRs very soon. But I can't take responsibility for maintaining this project in the future. 

Anyway, I can help you at least with some issues.

**Comment by wabilin** [comment]
Hi, I am a user of this this package.
Thanks for this great work, it's so important for vim users who likes easy-motion.

I saw this issue and read the code.
I am glad to help maintaining and improving this package.

**Comment by leny** [comment]
**wabilin** > thanks! I've sent you an invite!

**Comment by wabilin** [comment]
Thank you!
