### ISSUE TITLE
Select vs. go to

### ISSUE THREAD

**Issue by instanceofme** [leny/atom-easy-motion-redux#3]
There's a comparable IntelliJ IDEA plugin called [AceJump](http://plugins.jetbrains.com/plugin?pluginId=7086) that has a clever twist: when selecting the position via the letter, pressing simply the letter key would jump to the position, whereas pressing Shift + the letter key would select from the current position to the destination.

This feature would be rather nice :)

**Comment by leny** [comment]
Hi, thanks for the idea.

I will definitely try to implement it. Probably tonight, or tomorrow.

**Comment by kerbyfc** [comment]
+1, it will be really cool! Thanks for the plugin! Take my star %)

**Comment by kerbyfc** [comment]
Oh! It' will be superior, if the vim visual mode will be supported! There are no donate section in readme ;)

**Comment by kerbyfc** [comment]
Sorry for my english )

**Comment by leny** [comment]
I'm quite busy for now, will definitely try to made this when I got some time.

Feel free to propose a Pull Request if you feel adventurous ;)

**Comment by obenjiro** [comment]
Made a pull request, plz review

**Comment by leny** [comment]
Merged and published as 1.1.0.

Thanks @aiboy
