### ISSUE TITLE
Use different alphabet by default

### ISSUE THREAD

**Issue by dzhlobo** [leny/atom-easy-motion-redux#32]
By default, we use "ABCDEF..." symbols for jumping across the text. But usually, people keep their fingers above "asdf" and "jkl;" keys. So I suggest to use them first by default.

See my current settings:
<img width="504" alt="screen shot 2018-12-07 at 13 53 59" src="https://user-images.githubusercontent.com/800337/49643755-96794a80-fa27-11e8-81d7-99837b571347.png">

We may research what are most "accessible" keys and make them default.

**Comment by wabilin** [comment]
#34 changed default characters to `ASDFJKLGHQWERTYUIOPZXCVBNM`
But I noticed that they would show from the highest row to lowest row.
Maybe order by distance to the cursor would be better?

**Comment by wabilin** [comment]
I found that order from top to bottom is good enough, just like in spacemacs.
